package car_rpc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-07T11:05:40.968+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://informatique.polytech.unice.fr/soa1/cookbook/", name = "CarRental")
@XmlSeeAlso({ObjectFactory.class})
public interface CarRental {

    @WebMethod
    @RequestWrapper(localName = "getCars", targetNamespace = "http://informatique.polytech.unice.fr/soa1/cookbook/", className = "car_rpc.GetCars")
    @ResponseWrapper(localName = "getCarsResponse", targetNamespace = "http://informatique.polytech.unice.fr/soa1/cookbook/", className = "car_rpc.GetCarsResponse")
    @WebResult(name = "carSearch_result", targetNamespace = "")
    public java.util.List<car_rpc.Car> getCars(
        @WebParam(name = "place", targetNamespace = "")
        java.lang.String place,
        @WebParam(name = "duration", targetNamespace = "")
        int duration
    );
}
