version: "2"
services:
  tcs-carrental-service:
    command: npm start
    container_name: tcs-carrental-resource-container
    image: iliasnaamane/tcs-carrental
    ports:
      - "8080:8080"
    links:
      - database
    environment:
      - MONGODB_ADDRESS=database
  database:
    image: mongo
    container_name: database-container
    volumes:
      - "./mongo_data:/data/db"
    environment:
      - MONGODB_DATABASE=CarRentDB
    ports:
      - "27017:27017"
