version: "2"
services:
  businesstravel-resource-service:
    command: npm start
    container_name: tcs-businesstravel-container
    image: iliasnaamane/tcs-businesstravel-image
    ports:
      - "8080:8080"
    links:
      - database
    environment:
      - MONGODB_ADDRESS=database
  database:
    image: mongo
    container_name: tcs-database
    volumes:
      - "./mongo_data:/data/db"
    environment:
      - MONGODB_DATABASE=BusinessTravelDB
    ports:
      - "27017:27017"
