version: '2'

services:

  hotel-rpc:                
    container_name: hotel-rpc
    image: result/hotel-rpc
    ports:
      - "9010:8080"

  car-rpc:
    container_name: car-rpc
    image: result/car-rpc
    ports:
      - "9020:8080"


  vols-doc:
    container_name: vols-doc
    image: result/vols-doc
    ports:
      - "9030:8080"

  