version: '2'

services:

  hotel-rpc:                
    container_name: hotel-rpc
    image: result/hotel-rpc
    ports:
      - "9010:8080"

  car-rpc:
    container_name: car-rpc
    image: result/car-rpc
    ports:
      - "9020:8080"


  vols-doc:
    container_name: vols-doc
    image: result/vols-doc
    ports:
      - "9030:8080"
  tcs-businesstravel-service:
    command: npm start
    container_name: businesstravel-resource
    image: result/businesstravel-resource
    ports:
      - "9040:8080"
    links:
      - database
    environment:
      - MONGODB_ADDRESS=database
  database:
    image: mongo
    container_name: database-container
    volumes:
      - "./mongo_data:/data/db"
    environment:
      - MONGODB_DATABASE=BusinessTravelDB
    ports:
      - "27017:27017"