package hotel_rpc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-07T00:02:47.085+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "Hotel_Service", 
                  wsdlLocation = "file:/home/user/Téléchargements/Integration%20service/tests/acceptation/src/main/resources/HOTEL.wsdl",
                  targetNamespace = "Hotel_RPC") 
public class HotelService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("Hotel_RPC", "Hotel_Service");
    public final static QName HotelPort = new QName("Hotel_RPC", "Hotel_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/user/Téléchargements/Integration%20service/tests/acceptation/src/main/resources/HOTEL.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/user/Téléchargements/Integration%20service/tests/acceptation/src/main/resources/HOTEL.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HotelService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HotelService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HotelService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HotelService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HotelFinder
     */
    @WebEndpoint(name = "Hotel_Port")
    public HotelFinder getHotelPort() {
        return super.getPort(HotelPort, HotelFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelFinder
     */
    @WebEndpoint(name = "Hotel_Port")
    public HotelFinder getHotelPort(WebServiceFeature... features) {
        return super.getPort(HotelPort, HotelFinder.class, features);
    }

}
