package hotel_rpc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-07T11:05:40.457+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://informatique.polytech.unice.fr/soa1/cookbook/", name = "HotelFinder")
@XmlSeeAlso({ObjectFactory.class})
public interface HotelFinder {

    @WebMethod
    @RequestWrapper(localName = "recherche", targetNamespace = "http://informatique.polytech.unice.fr/soa1/cookbook/", className = "hotel_rpc.Recherche")
    @ResponseWrapper(localName = "rechercheResponse", targetNamespace = "http://informatique.polytech.unice.fr/soa1/cookbook/", className = "hotel_rpc.RechercheResponse")
    @WebResult(name = "recherche_hotel", targetNamespace = "")
    public hotel_rpc.Hotel recherche(
        @WebParam(name = "lieu", targetNamespace = "")
        java.lang.String lieu,
        @WebParam(name = "dure", targetNamespace = "")
        int dure
    );
}
